angular.module("app",["param","cache","tagSystem"])
.config(['$compileProvider',function($compileProvider){
	$compileProvider.aHrefSanitizationWhitelist(/^\s*(https?|ftp|mailto|tel|file|blob):/);
}])
.run(["$rootScope",function($rootScope){
	$rootScope.__proto__.confirm=window.confirm.bind(window);			
	$rootScope.__proto__.alert=window.alert.bind(window);
	$rootScope.__proto__.isNaN=window.isNaN.bind(window);
	$rootScope.__proto__.Date=window.Date;
	$rootScope.__proto__.Math=window.Math;
}]);